In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression,LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv("loanf.csv")

In [3]:
df.columns

Index(['Interest.Rate', 'FICO.Score', 'Loan.Length', 'Monthly.Income',
       'Loan.Amount'],
      dtype='object')

In [4]:
df["FICO.Score"].values

array([670, 670, 665, ..., 810, 765, 740], dtype=int64)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2500 entries, 6 to 2497
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Interest.Rate   2500 non-null   float64
 1   FICO.Score      2500 non-null   int64  
 2   Loan.Length     2500 non-null   int64  
 3   Monthly.Income  2499 non-null   float64
 4   Loan.Amount     2500 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 117.2 KB


In [6]:
df.describe()

Interest.Rate   FICO.Score  Loan.Length  Monthly.Income   Loan.Amount
count    2500.000000  2500.000000  2500.000000     2499.000000   2500.000000
mean       13.066996   705.888000    41.260800     5688.931321  12406.500000
std         4.178230    35.033161     9.930893     3963.118185   7801.544872
min         5.420000   640.000000    36.000000      588.500000   1000.000000
25%        10.160000   680.000000    36.000000     3500.000000   6000.000000
50%        13.110000   700.000000    36.000000     5000.000000  10000.000000
75%        15.800000   725.000000    36.000000     6800.000000  17000.000000
max        24.890000   830.000000    60.000000   102750.000000  35000.000000

In [7]:
df.count()

Interest.Rate     2500
FICO.Score        2500
Loan.Length       2500
Monthly.Income    2499
Loan.Amount       2500
dtype: int64

In [8]:
x=df[["FICO.Score","Loan.Amount"]].values
y=df["Interest.Rate"]

In [9]:
x

array([[  670,  6000],
       [  670,  2000],
       [  665, 10625],
       ...,
       [  810, 27000],
       [  765, 25000],
       [  740, 16000]], dtype=int64)

In [10]:
lr_model=LinearRegression()
lr_model=lr_model.fit(x,y)

In [11]:
y_pred=lr_model.predict(x)

In [12]:
log = 1/(1+np.exp(-y_pred))

In [13]:
#Logistic Regression

In [14]:
df["TF"]=df["Interest.Rate"]<17

In [15]:
df.head()

Interest.Rate  FICO.Score  Loan.Length  Monthly.Income  Loan.Amount     TF
6           15.31         670           36         4891.67         6000   True
11          19.72         670           36         3575.00         2000  False
12          14.27         665           36         4250.00        10625   True
13          21.67         670           60        14166.67        28000  False
21          21.98         665           36         6666.67        22000  False

In [16]:
x=df[["FICO.Score","Loan.Amount"]].values
y=df["TF"].values

In [17]:
df.TF.value_counts()

True     2032
False     468
Name: TF, dtype: int64

In [18]:
log_model=LogisticRegression()
log_model=log_model.fit(x,y)

In [19]:
log_model.predict([[493,20000]])

array([ True])

In [20]:
log_model.predict_proba([[493,20000]])

array([[0.49939985, 0.50060015]])

In [21]:
def Loan_Approve(Fico,Amount):
    out=log_model.predict_proba([[Fico,Amount]])
    if out[0][1]>0.8:
        print("Loan will Approve")
    else:
        print("Loan will not Approve")

In [22]:
Loan_Approve(375,2000)

Loan will Approve


In [23]:
from ipywidgets import interact

In [24]:
interact(Loan_Approve,Fico=(0,1000),Amount=(200,20000))

interactive(children=(IntSlider(value=500, description='Fico', max=1000), IntSlider(value=10100, description='…

<function __main__.Loan_Approve(Fico, Amount)>

In [25]:
X=int(input("Enter your Fico Score: "))
Y=int(input("Enter your Loan Amount: "))
print(Loan_Approve(X,Y))


Enter your Fico Score: 200
Enter your Loan Amount: 2000
Loan will not Approve
None


In [26]:
y_pred=log_model.predict(x)

In [27]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [28]:
cm=confusion_matrix(y,y_pred)

In [29]:
cm

array([[  75,  393],
       [  39, 1993]], dtype=int64)

In [30]:
accuracy_score(y,y_pred)

0.8272

In [31]:
def Accuracy_score(act,pred):
    data=zip(act,pred)
    total_correct=0
    total_data=len(act)
    for y,y_pred in data:
        if y == y_pred:
            total_correct+=1
    return(total_correct/total_data)

In [32]:
Accuracy_score(y,y_pred)

0.8272

In [52]:
np.unique(y)

array([False,  True])

In [53]:
np.zeros((len(np.unique(y)),len(np.unique(y))))

array([[0., 0.],
       [0., 0.]])

In [42]:
def comp_confmat(actual, predicted):

    classes = np.unique(actual) # extract the different classes
    matrix = np.zeros((len(classes), len(classes))) # initialize the confusion matrix with zeros

    for i in range(len(classes)):
        for j in range(len(classes)):

            matrix[i, j] = np.sum((actual == classes[i]) & (predicted == classes[j]))

    return matrix

In [43]:
comp_confmat(y,y_pred)

array([[  75.,  393.],
       [  39., 1993.]])

In [54]:
from sklearn.externals import joblib
joblib.dump(log_model,"loan_approve_or_not_model.pkl")

C:\Users\lenevo\anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


['loan_approve_or_not_model.pkl']